### ISSUE TITLE
WCIP-1: WalletConnect v1.0 protocol spec

### ISSUE THREAD

**Issue by ligi** [WalletConnect/WCIPs#1]
I think v1.0 should get a WCIP where we specify the protocol including all the ideas that recently where discussed in the walletconnect forum. 
The main idea was to move information from the QR-Code and bridge to one initial session object. I would want to add 2 more things: rendezvous points (think the future libp2p feature) and a version field (perhaps then we don't even need the version from  EIP1328)

so the initial session data would include:
 * protocol version
 * dapp name
 * [MultiHash to logo?]
 * listOf(rendezvous points)
 * listOf(initialCalls)

I would suggest the URL for the QR code to look like this

wc:<MultiHash(initial_session_data)>/session_key[?bridge=bridge_url]

in the future we might even be able to get rid of bridge_url

**Comment by pedrouid** [comment]
Agreed, let's start drafting the spec of what v1.0 will look like.

Currently in the v0.8, I have made the following changes (as of 14 Dec 2018):
- Session requests require `chainId` and `accounts`
- Custom error messages can be included on rejected session/call requests
- Bridge Server does not store any push notification data
- WalletConnect URI does not include a dappName

We should also make it clear which data is included in the URI and which is part of the session request. The URI should include the minimum data required to establish a connection between the Dapp and the Wallet, currently this includes `bridgeUrl`, `symKey` and `sessionId`. Any other data that is accessory to completing the handshake should be relayed as part of the session request, this may include `dappData` (which would include the dappName, contractAddress, logo, url, etc), `listOfInitialCalls` and `listOfRedenzvousPoints`.

Regarding the protocol version number, I agree that it might not be necessary as we can generalize the required fields to be more transport-agnostic for future implementations. We could potentially name the `bridge` to `rendezvous`/`star`/`node` which may include an endpoint to an bridge url, ethereum node, ipfs node, libp2p star or webrtc signalling server.

However a counter-argument to removing the version number is that this allows for future versioning if these handshakes change considerably.

Regarding the `sessionId` I'm still unsure what a good alternative would be other than the current uuid v4. I remember we discussed in the past to construct a hash from the two clients' address/id but this would require the Dapp to know the Wallet address/id. Potentially we could replace it with a `peerId` that would allow the counter-party to subscribe for a session request from this `peerId` that could directly target to send a response to the session request.

I would also would like to add again that the `wc:` schema has a weird english connotation to toilets and having only two characters can be too prone to collude with potentially other schemas. Thus I would like to propose `walletconnect:`. I think the URI proposed is already sufficiently short to use this schema without reducing the "scannability" of QR Codes.

Putting together all of my proposals for the WalletConnect v1.0 session handshake. I would purpose the following URI:

```
walletconnect:<peer_id>@<version_id>?node=<node_endpoint>&key=<sym_key>
```

The Dapp would then push a session request with an encrypted payload containing:
- dappData (potentially renamed to peerData)
- initialCallRequests
- rendezvousEndpoints

The Wallet can fetch/subscribe to this session request and read this data using the provided `symKey` and display it to the user for making an informed decision on the approval or rejection of this session request.

Consequently it would push the session status to the provided `nodeEndpoint` to be relayed to the Dapp which would received a targeted encrypted payload using the provided `peerId` on the URI.

The Dapp could read this data using the `symKey` and obtaining the following information:
- walletData (this was recently suggested as an optional parameter on Telegram -  can be renamed to peerData)
- chainId
- accounts
- initialCallStatuses (results from the provided initialCallRequests)
- rendezvousEndpoints (intersection of matching rendezevousEndpoints of both peers)

After writing down all of this reasoning, I'm now more certain that a `peerId` would be more efficient than a `sessionId` since these communications are always one-to-one.

**Comment by ligi** [comment]
Yea wc might have a bad connotation in english - but no user really sees this and some chars can really make a difference in QR codes. See e.g. on this console - some chars can make the difference between scanable and unscanable ..
![img_20181214_165045](https://user-images.githubusercontent.com/111600/50013524-a4980f80-ffc1-11e8-8c5a-5b8efff5bee0.jpg)

you will not really enter these URLs - they will be either hidden behind QR codes, or a link or behind some other representation where the users are not exposed to the shitty connotation..-)
